#   ########################################################################
#   Copyright 2021 Splunk Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#   ########################################################################

name: ci-release
on:
  push:
    branches:
      - "main"
      - "develop"
      - "next"
    tags-ignore:
      - "v*"

jobs:
  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          persist-credentials: false

      #Build docker images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta - frontend
        id: docker_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/splunk/sc4snmp-ui/frontend/container
          tags: |
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}}
            type=ref,event=branch
      - name: Build and push action - frontend
        id: docker_action_build_frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-to: type=inline
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.12"

  build-backend:
    name: build-backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          persist-credentials: false

      #Build docker images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta - backend
        id: docker_meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/splunk/sc4snmp-ui/backend/container
          tags: |
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}}
            type=ref,event=branch
      - name: Build and push action - backend
        id: docker_action_build_backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-to: type=inline
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.12"
  release:
    name: Release
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          persist-credentials: false
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.12"
      - name: Semantic Release
        id: version
        uses: cycjimmy/semantic-release-action@v4.1.0
        with:
          semantic_version: 21.1.1
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
            semantic-release-replace-plugin@1.2.7
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_ADMIN }}

